name: 1 - Feature (Terraform)

on:
  push:
    branches:
      - feature/*

permissions:
  id-token: write # obrigatório para usar autenticação OIDC
  contents: write # obrigatório para clonar o código do repositório

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME}}
          role-duration-seconds: ${{ secrets.AWS_ROLE_DURATION_SECONDS }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Terraform Init
        run: terraform init

  create-pull-request:
    
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        if: ${{ success() }}
        uses: peter-evans/create-pull-request@v3
        with:
          title: PR criado automaticamente
          body: Caso seu build de feature for realizado com sucesso, você poderá seguir para o planejamento de sua infra na develop
          base: develop
          branch: "feature/*"
          token: ${{ secrets.GITHUB_TOKEN }}