name: 3 - Develop (Terraform)

on:
  push:
    branches:
      - develop

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Create Pull Request
        if: ${{ success() }}
        uses: peter-evans/create-pull-request@v3
        with:
          title: PR criado automaticamente
          body: Caso seu build de feature for realizado com sucesso, você poderá seguir para o planejamento de sua infra na develop
          branch: develop
          token: ${{ secrets.GITHUB_TOKEN }}