name: 3 - Develop (Terraform)

on:
  push:
    branches:
      - develop

permissions:
  id-token: write # obrigatório para usar autenticação OIDC
  contents: read # obrigatório para clonar o código do repositório

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME}}
          role-duration-seconds: ${{ secrets.AWS_ROLE_DURATION_SECONDS }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Create Pull Request
        if: ${{ success() }}
        uses: peter-evans/create-pull-request@v3
        with:
          title: PR criado automaticamente
          body: Caso seu build da develop for realizado com sucesso, você poderá seguir para implantação em produção
          branch: main
          token: ${{ secrets.GITHUB_TOKEN }}